Atri-Labs/framework-docs

docs/create-app.md

reason: one user made this mistake

added function inside which code is to be written

---

sidebars.js

Thank you for your contribution to the documentation of Atri framework. 
Before submitting this PR, please make sure:
```
$ yarn build
```

moved up "existing project" and "deployment"

---

docs/comp-reference/basics/upload.md
docs/guides-backend/send-image-from-backend.md
docs/utilities/chart-data-utils/draw-chart.md
docs/utilities/chart-data-utils/parse-charts-data.md
docs/utilities/image-utils/change-background.md
docs/utilities/image-utils/create-media-response.md
docs/utilities/image-utils/parse-uploaded-file.md
docs/utilities/image-utils/remove-background.md
sidebars.js

Thank you for your contribution to the documentation of Atri framework. 
Before submitting this PR, please make sure:
```
$ yarn build
```

Added documentation of Draw Charts

---

blog/web_stack.md

- added placeholder for first blog
```
$ yarn build
```

added placeholder for first blog

---

docs/comp-reference/basics/dropdown.md
docs/comp-reference/basics/upload.md
sidebars.js

Add reference to a related issue that this PR is addressing. For example, fixes #
#21 Added doc for dropdowns
```
$ yarn build
```

Added doc for dropdown

---

docusaurus.config.js

closed #59
1. Added company Twitter link in footer
2. Changed category: `More` -> `Social`
```
$ yarn build
```

added twitter link in footer

---

docs/intro.md

fixed link to gif in intro page
```
$ yarn build
```

updated link to gif

---

docs/tutorials/personal_website.md

We released a new video tutorial series on how to create a portfolio website. This PR adds the video in tutorial section to point users ti that resource. 
```
$ yarn build
```

added navbar video in tutorial section

---

docs/deploy-app/deploy-ghpages.md
docs/getting-started/installation/install_with_pipenv.md

Fixes #74 
- updated syntax so that words in code blocks don't get randomly italicized
```
$ yarn build
```

fixed random italicization after = sign in code block

---

docs/troubleshoot/atri_start.md
docs/troubleshoot/installation_error.md
sidebars.js

Closed #64 
```
$ yarn build
```

Added atri start --debug

---

docs/troubleshoot/installation_error.md

added 1st solution in installation bug

---

docs/troubleshoot/atri_start.md
docs/troubleshoot/installation_error.md

Added solution for pipenv not found error
```
$ yarn build
```

Added solution for pipenv not found error

---

docs/troubleshoot/atri_start.md
docs/troubleshoot/installation_error.md

Added atri_utils
```
$ yarn build
```

Added atri_utils error

---

docs/troubleshoot/installation_error.md

added process error

---

docs/troubleshoot/atri_start.md

Added fastapi error fix
```
$ yarn build
```

added fastapi error fix

---

docs/troubleshoot/installation_error.md

Added pre-existing Pipfile installation error
```
$ yarn build
```

added pre-existing Pipfile installation error

---

docs/troubleshoot/atri_start.md
docs/troubleshoot/installation_error.md

Added error: Failed building wheel for yarl
```
$ yarn build
```

Added error: Failed building wheel for yarl

---

docs/troubleshoot/prereq.md
sidebars.js

Added prerequisites file & OSError fix
```
$ yarn build
```

Added prerequisites file & OSError fix

---

docs/troubleshoot/installation_error.md

added pipenv not recognized as cmdlet error

---

docs/getting-started/installation/install_prereqs.md
docs/getting-started/installation/install_with_conda.md
docs/getting-started/installation/install_with_pipenv.md

Added terminal related instruction for Windows users
```
$ yarn build
```

Added terminal related instruction for Windows users

---

docs/getting-started/installation/install_prereqs.md
docs/getting-started/installation/install_with_conda.md
docs/getting-started/installation/install_with_pipenv.md

Add reference to a related issue that this PR is addressing. For example, fixes #
```
$ yarn build
```

added space character

---

docs/getting-started/create-app.md
docs/getting-started/installation/install_prereqs.md
docs/getting-started/installation/install_with_conda.md
docs/getting-started/installation/install_with_pipenv.md

fixed links to troubleshooting pages

---

docs/getting-started/create-app.md
docs/getting-started/installation/install_prereqs.md
docs/getting-started/installation/install_with_conda.md
docs/getting-started/installation/install_with_pipenv.md

changed heading no

---

docs/existing-project/update-atri.md

added install atri in update

---

docs/troubleshoot/start_error.md

updated solution for atri_utils

---

blog/2023-02-7-welcome/index.md

removed link to getting started
